---
- name: Node Exporter
  hosts: prometheus_node_exporter
  become: true
  become_user: root
  become_method: sudo
  roles:
    - prometheus_node_exporter

- name: RabbitMQ Exporter
  hosts: prometheus_rabbitmq_exporter
  become: true
  become_user: root
  become_method: sudo
  roles:
    - prometheus_rabbitmq_exporter

- name: docker Exporter
  hosts: prometheus_docker_exporter
  become: true
  become_user: root
  become_method: sudo
  roles:
    - prometheus_docker_exporter

- name: Mysql Exporter
  hosts: prometheus_mysql_exporter
  become: true
  become_user: root
  become_method: sudo
  roles:      
    - prometheus_mysql_exporter  

- name: Prometheus
  hosts: prometheus
  become: true
  become_user: root
  become_method: sudo
  roles:
    - prometheus 

- name: Grafana
  hosts: grafana
  become: true
  become_user: root
  become_method: sudo
  roles:
    - grafana
